/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package factsView;

import controladorRegistro.Controlador;
import factsModel.Producte;
import mainFacts.menuDigital;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class mostrarProductes extends javax.swing.JPanel {

    private HashMap<Integer, Producte> productes;
    private Controlador controlador;
    private menuDigital menuDigital;
    private mostrarProductes estaVentana;

    /**
     * Creates new form mostrarProductes
     */
    public mostrarProductes(java.awt.Frame parent, boolean modal) {
        initComponents();
        controlador = Controlador.getInstance();
        menuDigital = (menuDigital) parent;
        estaVentana = this;

        updateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

//Per mostrar la tabla de mostra del producte
    public void updateTable() {
        productes = (HashMap<Integer, Producte>) Controlador.getInstance().getProductes();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Codigo", "Tipo Producto", "Precio", "tematica"});
        for (Producte c : productes.values()) {
            dtm.addRow(c.toArrayString());
        }
        jTable1.setModel(dtm);
    }
}
