/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package factsView;

import mainFacts.menuDigital;
import Persistencia.Fitxero;
import factsModel.Cliente;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class regitstrarClients extends javax.swing.JFrame {

    /**
     * Creates new form regitstrarClients
     */
    public regitstrarClients(menuDigital aThis) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("NIF:");

        jLabel6.setText("Nom:");

        jLabel7.setText("Direcció:");

        jLabel8.setText("Número de telèfon:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField3)
                        .addComponent(jTextField2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regitstrarClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regitstrarClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regitstrarClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regitstrarClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    public class GestioClientsGUI extends javax.swing.JFrame {

        private static HashMap<String, Cliente> clients;
        private Fitxero fitxer;

        public GestioClientsGUI(HashMap<String, Cliente> clients, Fitxero fitxer) {
            this.clients = clients;
            this.fitxer = fitxer;
            initComponents();
            setLocationRelativeTo(null);
        }

        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {
            panellRegistre = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            campNIF = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            campNom = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            campDireccio = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            campNumero = new javax.swing.JTextField();
            botoRegistrar = new javax.swing.JButton();
            botoNetejar = new javax.swing.JButton();
            panellConsulta = new javax.swing.JPanel();
            jScrollPane1 = new javax.swing.JScrollPane();
            areaConsulta = new javax.swing.JTextArea();
            botoConsultar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Gestió de Clients - FACTS");

            panellRegistre.setBorder(javax.swing.BorderFactory.createTitledBorder("Registre de Clients"));
            panellRegistre.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

            jLabel1.setText("NIF:");
            panellRegistre.add(jLabel1);
            panellRegistre.add(campNIF);

            jLabel2.setText("Nom:");
            panellRegistre.add(jLabel2);
            panellRegistre.add(campNom);

            jLabel3.setText("Direcció:");
            panellRegistre.add(jLabel3);
            panellRegistre.add(campDireccio);

            jLabel4.setText("Número de telèfon:");
            panellRegistre.add(jLabel4);
            panellRegistre.add(campNumero);

            botoRegistrar.setText("Registrar Client");
            botoRegistrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botoRegistrarActionPerformed(evt);
                }
            });
            panellRegistre.add(botoRegistrar);

            botoNetejar.setText("Netejar Camps");
            botoNetejar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botoNetejarActionPerformed(evt);
                }
            });
            panellRegistre.add(botoNetejar);

            getContentPane().add(panellRegistre, java.awt.BorderLayout.NORTH);

            panellConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Clients"));
            panellConsulta.setLayout(new java.awt.BorderLayout());

            areaConsulta.setColumns(20);
            areaConsulta.setFont(new java.awt.Font("Monospaced", 0, 12));
            areaConsulta.setRows(5);
            areaConsulta.setEditable(false);
            jScrollPane1.setViewportView(areaConsulta);

            panellConsulta.add(jScrollPane1, java.awt.BorderLayout.CENTER);

            botoConsultar.setText("Consultar Tots els Clients");
            botoConsultar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botoConsultarActionPerformed(evt);
                }
            });
            panellConsulta.add(botoConsultar, java.awt.BorderLayout.SOUTH);

            getContentPane().add(panellConsulta, java.awt.BorderLayout.CENTER);

            pack();
        }// </editor-fold>                        
//Per poder entrar al registre
        private void botoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {
            registrarClient();
        }
// Els esborra
        private void botoNetejarActionPerformed(java.awt.event.ActionEvent evt) {
            netejarCamps();
        }

        private void botoConsultarActionPerformed(java.awt.event.ActionEvent evt) {
            consultarClients();
        }
//Apartat per poder registrar els clients
        private void registrarClient() {
            try {
                String nif = campNIF.getText().trim();
                String nom = campNom.getText().trim();
                String direccio = campDireccio.getText().trim();
                String numeroText = campNumero.getText().trim();

                if (nif.isEmpty() || nom.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Els camps NIF i Nom són obligatoris", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                int numero = 0;
                if (!numeroText.isEmpty()) {
                    try {
                        numero = Integer.parseInt(numeroText);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "El número de telèfon ha de ser un valor numèric", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                Cliente nouClient = new Cliente(nif, nom, direccio, numero);

                if (clients.containsKey(nouClient.getNif())) {
                    JOptionPane.showMessageDialog(this, "Ja existeix un client amb aquest NIF", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                clients.put(nouClient.getNif(), nouClient);
                fitxer.writerCliente(nouClient);

                JOptionPane.showMessageDialog(this, "Client registrat amb èxit", "Èxit", JOptionPane.INFORMATION_MESSAGE);
                netejarCamps();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error en desar el client al fitxer: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error en registrar el client: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
//per verificar els clients
        private void consultarClients() {
            if (clients.isEmpty()) {
                areaConsulta.setText("No hi ha clients registrats.");
                return;
            }

            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-15s %-20s %-30s %-15s\n", "NIF", "NOM", "DIRECCIÓ", "TELÈFON"));
            sb.append("-----------------------------------------------------------------\n");

            for (Cliente c : clients.values()) {
                sb.append(String.format("%-15s %-20s %-30s %-15d\n",
                        c.getNif(),
                        c.getNom(),
                        c.getDireccio(),
                        c.getNumero()));
            }

            areaConsulta.setText(sb.toString());
        }
//Se elimina els apartats
        private void netejarCamps() {
            campNIF.setText("");
            campNom.setText("");
            campDireccio.setText("");
            campNumero.setText("");
            campNIF.requestFocus();
        }
//Aquest obre la part de mostrar
        public void obrirInterficie(HashMap<String, Cliente> clients) {
            {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new GestioClientsGUI(clients, fitxer).setVisible(true);
                    }
                });
            }
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea areaConsulta;
    private javax.swing.JButton botoConsultar;
    private javax.swing.JButton botoNetejar;
    private javax.swing.JButton botoRegistrar;
    private javax.swing.JTextField campDireccio;
    private javax.swing.JTextField campNIF;
    private javax.swing.JTextField campNom;
    private javax.swing.JTextField campNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panellConsulta;
    private javax.swing.JPanel panellRegistre;
    // End of variables declaration                   
}
